/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Entity.Entity;
import Model.SmartTransactions;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import smart.Smart;

/**
 *
 * @author Paul Andre Francisco
 */
public class Index extends javax.swing.JFrame{      
                
    /**
     * Creates new form Index
     */
    public Index() throws ClassNotFoundException, SQLException {
        initComponents();   
        displayRecords();
    }
    
    public void displayRecords() throws ClassNotFoundException, SQLException{        
        DefaultTableModel model = new DefaultTableModel();        
        Object[] columnsName = new Object[12];
        
        /* Header Fields */
        columnsName[0] = "Smart Number";
        columnsName[1] = "Reference Number";
        columnsName[2] = "Type";
        columnsName[3] = "Amount";
        columnsName[4] = "Balance";        
        columnsName[5] = "Sender Name";
        columnsName[6] = "Sender No";
        columnsName[7] = "Sender Address";
        columnsName[8] = "Receiver Name";
        columnsName[9] = "Receiver No";
        columnsName[10] = "Receiver Address";
        columnsName[11] = "Transaction Date";
        
        model.setColumnIdentifiers(columnsName);
        Object[] rowData = new Object[12];     
        
        int counter = getEntity().size();
        int i;
        
        /* Data from Table */
        for(i = 0; i < counter; i++)
        {   
            rowData[0] = getEntity().get(i).getSmartNo();
            rowData[1] = getEntity().get(i).getRefNo();
            rowData[2] = getEntity().get(i).getType();
            rowData[3] = getEntity().get(i).getAmount();
            rowData[4] = getEntity().get(i).getBalance();            
            rowData[5] = getEntity().get(i).getSender();
            rowData[6] = getEntity().get(i).getSenderNo();
            rowData[7] = getEntity().get(i).getSenderAdd();
            rowData[8] = getEntity().get(i).getReceiver();
            rowData[9] = getEntity().get(i).getReceiverNo();
            rowData[10] = getEntity().get(i).getReceiverAdd();
            rowData[11] = getEntity().get(i).getCreateDate();
            
            model.addRow(rowData);                        
        }
        
        jTable1.setModel(model);
    }
    
    static ArrayList<Entity> getEntity() throws ClassNotFoundException, SQLException
    {
        ArrayList<Entity> entityList = new ArrayList<Entity>();
        Entity entity;
        SmartTransactions transactions = new SmartTransactions();
        ResultSet records = transactions.getRecords(null, null);
                
        while (records.next())
        {           
            entity = new Entity(
                records.getInt("smart_no"),
                records.getString("ref_no"),
                records.getString("type"),
                records.getBigDecimal("amount"),
                records.getBigDecimal("balance"),                
                records.getString("sender"),
                (int) records.getLong("sender_no"),
                records.getString("sender_add"),
                records.getString("receiver"), 
                (int) records.getLong("receiver_no"),
                records.getString("receiver_add"),
                records.getString("create_date")
            );
            
            entityList.add(entity);
        }
        
        return entityList;        
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Add = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("View Records");
        setBackground(new java.awt.Color(0, 0, 0));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        jTable1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Reference Number", "Transaction Type", "Amount", "Balance", "Sender Name", "Sender Number", "Sender Address", "Receiver Name", "Receiver Number", "Receiver Address", "Transaction Date"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jMenu1.setText("File");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jMenu1, org.jdesktop.beansbinding.ELProperty.create("Add New"), jMenu1, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        Add.setText("Add Transaction");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        jMenu1.add(Add);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Search");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 918, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try
                {                                                
                    try {
                        new Index().setVisible(true);
                    } 
                    catch (SQLException ex) {
                        Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                catch (ClassNotFoundException ex) 
                {
                    Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Add;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
